### PR TITLE
Fixed Rep socket panic when message comes from Dealer.

### LINKED ISSUE #132: Rep socket panics when message comes from Dealer
I get panic on message arrival when Rep socket is connected to Dealer socket. Sending message directly from Req to Rep works fine.

```
thread 'tokio-runtime-worker' panicked at 'assertion failed: m.pop_front().unwrap().is_empty()', /home/karmo/.cargo/git/checkouts/zmq.rs-12939e22dc7edef4/511240e/src/rep.rs:144:29
```

This is debugged message before panic:
```
ZmqMessage {
    frames: [
        b"\xf9\x89\xd5\x97x\x9c@\x9c\x9f\xa5\xd4\xb6\xc7\xcb\xd0\xb6",
        b"",
        b"Hello",
    ],
}
```

Sending message like this: `req_socket.send("Hello".into()).await?;`

Setup: Req -> Router <- proxy() -> Dealer <- Rep

I managed to fix it locally. Planning to open a PR soon.

### PR DESCRIPTION
**Pull request by karmux**
Fixes #132

### CODE REVIEW

File: src/rep.rs [hunk 1]
```diff
@@ -140,6 +146,10 @@ impl SocketRecv for RepSocket {
                     match message {
                         Message::Message(mut m) => {
                             assert!(m.len() > 1);
+                            if m.len() > 2 {
+                                self.connection_id =
```
Comment (Alexei-Kornienko) [inline src/rep.rs:150]: Taken from ZMQ spec (https://rfc.zeromq.org/spec/28/)
* An address envelope consisting of zero or more frames, each containing one identity.
For processing incoming messages:
* SHALL remove and store the address envelope, including the delimiter.

So potentially it can be more than one identity in a message. IMHO a better approach would be to store ZmqMessage in the socket - it would contain all frames up to delimiter and later we could just attach reply to it and send it down the wire

**Review by Alexei-Kornienko — COMMENTED** [review]
Thanks for your MR. I've added some inline comments cause it seems to be a partial fix and not fully compliant to spec. IMHO we should modify MR a little to make it fully compliant.

**Comment by Alexei-Kornienko** [comment]
It might be useful to add some kind of `split_to` method to ZmqMessage to make it easy to split frames apart. As well as `extend` to combine 2 messages into 1

File: src/message.rs [hunk 2]
```diff
@@ -53,6 +53,32 @@ impl ZmqMessage {
...
         self.frames
     }
+
+    pub fn prepend(&mut self, message: &ZmqMessage) {
+        for frame in message.iter().rev() {
+            self.push_front(frame.clone());
+        }
+    }
+
+    pub fn split_at(&self, mid: usize) -> (ZmqMessage, ZmqMessage) {
```
Comment (Alexei-Kornienko) [inline src/message.rs:63]: You could use split_off - https://doc.rust-lang.org/std/collections/struct.VecDeque.html#method.split_off

File: src/rep.rs [hunk 3]
```diff
@@ -114,6 +116,9 @@ impl SocketSend for RepSocket {
             Some(peer_id) => {
                 if let Some(mut peer) = self.backend.peers.get_mut(&peer_id) {
                     message.push_front(Bytes::from(""));
```
Comment (Alexei-Kornienko) [inline src/rep.rs:118]: Delimeter should be included in envelope

**Review by Alexei-Kornienko — COMMENTED** [review]
Just a minor coments otherwise LGTM

**Comment by Alexei-Kornienko** [comment]
Clippy sometimes becomes annoying.. 
LGTM^ minor issues might be fixed in subsequent requests
